# Site
repository: andypattonmorgan/andypattonmorgan.github.io
favicon: images/faviconmc.png

# Content configuration version
version: 2

# Personal info
name: Andy Patton-Morgan
title: Solutions Consultant IT Enterprise Operations
email: Andypattonmorgan@gmail.com
website: morgancraft.org

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: andypattonmorgan
github_username:  andypattonmorgan
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: andypattonmorgan
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: morgancraft.org
  icon: fas fa-globe
  url: https://www.morgancraft.org
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Leveraging 20+ years of Enterprise IT experience, I seek strategic roles that optimize value delivery. My expertise in engineering, project management, and process engineering empowers me to design and implement systems that enhance organizational efficiency, flexibility, and transparency. By understanding the intricate flow of work and value, I aim to create a more effective and predictable environment to track and achieve our goals.
  

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Kaiser Permanente
        link: KP.org
        # link_text: KP.org
        sub_title: Program Manager Consultant Specialist
        caption: May 1998 - Present
        quote: >
          When your work speaks for itself, don't interrupt - Henry J. Kaiser
        description: | # this will include new lines to allow paragraphs
            Kaiser Permanente is an American integrated managed care consortium, based in Oakland, California, United States. 
            Founded in 1945 by industrialist Henry J. Kaiser and physician Sidney Garfield.

  - title: Education and Certifications  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Diablo Valley College
        caption: 1991 - 1993
        sub_title: 
        quote: >
          # Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Television production and direction, philosopy.
        
      - layout: left
        title: Stanford Certified Project Manager
        caption: 2014
        sub_title: 
        quote: >
          # Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Television production and direction, philosopy.
          
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in IT Enterprise Socio-technical systems some of my other interests and hobbies are:
      - Jugger
      - Mace flow
      - Minecraft development with my children


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
